name: 'Asset & Artifact Downloader'
description: 'Downloads a release asset, file in Docker container, or artifact from a workflow run based on branch or sha'
inputs:
  owner:
    required: true
  repo:
    required: true
  file:
    description: 'A regex of which the first file found is downloaded'
    required: true
  target:
    description: 'A semver range matched to releases, or branch name, or sha'
    required: true
  prereleases:
    description: 'Whether or not to include prerelease versions when treating target as a release version'
    default: false
  container-package:
    description: 'If defined, target treated a release, and no asset found, look in a container package named this with release tag'
  artifact-name:
    description: 'When target is a branch or sha, the artifact name to look for the file in'
  token:
    required: true
    default: ${{github.token}}
  fail-on-missing-target:
    required: true
    default: true
    description: 'Whether to fail the step if target release file or artifact-name is not found'
  wait-for-exact-target:
    required: true
    default: false
    description: 'When target is a branch or sha, whether to wait up for workflow to complete on exact target or try parents'
outputs:
  downloaded-file:
    description: 'The name of the downloaded file, or empty string if failure'
runs:
  using: 'node16'
  main: 'dist/index.mjs'
